---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch.
  package:
    name: "{{ packages_name }}"
    state: present

- name: Set the bind address to a specific IP
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#network.host:'
    line: "network.host: {{ elasticsearch_network_host }}"
    backup: true

- name: Set a custom port for HTTP
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#http.port:'
    line: "http.port: {{ elasticsearch_http_port }}"
    backup: true

# - name: Force a restart if configuration has changed.
#   meta: flush_handlers

- name: Start Elasticsearch.
  service:
    name: "{{ service_name }}"
    state: "{{ service_service_state }}"
    enabled: "{{ service_service_enabled }}"

- name: Make sure Elasticsearch is running before proceeding.
  wait_for:
    host: "{{ elasticsearch_network_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 3
    timeout: 300
